service: task-manager-api

provider:
  name: aws
  runtime: python3.13
  stage: dev
  region: us-east-1
  environment:
    DB_STRING: ${env:DB_STRING}
    DB_NAME: ${env:DB_NAME}
    DB_TEST_NAME: ${env:DB_TEST_NAME}
    SECRET_KEY: ${env:SECRET_KEY}
    ACCESS_TOKEN_EXPIRE_MINUTES: ${env:ACCESS_TOKEN_EXPIRE_MINUTES}
    PYTHONPATH: "/var/runtime:/var/task:/opt/python"

package:
    exclude:
        - README.md
        - src/tests/**
        - node_modules/**
        - .serverless/**
        - package.json
        - package-lock.json
        - .pytest_cache
        - layer/**
        - layer.zip

functions:
  app:
    handler: src.main.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
    layers:
      - arn:aws:lambda:us-east-1:674949854599:layer:task-manager-api-layer:1
  
plugins:
  - serverless-python-requirements
  - serverless-offline
  
custom:
  pythonRequirements:
    dockerizePip: non-linux

resources:
  Outputs:
    ApiGatewayUrl:
      Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com"
